### ISSUE TITLE
Add exponential backoff to API calls for aws

### ISSUE THREAD

**Issue by vsoch** [converged-computing/cloud-select#19]
E.g., catch this:
```
 Traceback (most recent call last):
  File "/home/runner/.local/bin/cloud-select", line 8, in <module>
    sys.exit(run())
  File "/home/runner/.local/lib/python3.10/site-packages/cloud_select/client/__init__.py", line 350, in run
    main(args=args, parser=parser, extra=extra, subparser=helper)
  File "/home/runner/.local/lib/python3.10/site-packages/cloud_select/client/cache.py", line 30, in main
    cli.update_all()
  File "/home/runner/.local/lib/python3.10/site-packages/cloud_select/main/client.py", line 135, in update_all
    self.update_from_cache({}, "prices")
  File "/home/runner/.local/lib/python3.10/site-packages/cloud_select/main/client.py", line 156, in update_from_cache
    updated = func()
  File "/home/runner/.local/lib/python3.10/site-packages/cloud_select/main/cloud/aws/client.py", line 51, in prices
    response = self.pricing_cli.get_products(
  File "/home/runner/.local/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/runner/.local/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the GetProducts operation (reached max retries: 4): Rate exceeded
47107 total aws prices matching (***)...
```

**Comment by vsoch** [comment]
Fixed with #20
